apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clamav.fullname" . }}-notify
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.clamavNotify.volume.storageClass }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clamavNotify.volume.size }}Gi
