apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clamav-notify
spec:
  podSelector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-notify
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ include "clamav.fullname" . }}
    ports:
    - protocol: TCP
      port: 8080
