apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-config
data:
  clamd.conf: |
    LogTime yes
    LogClean yes
    LogSyslog no
    LogVerbose yes
    LogFile /dev/stdout
    DatabaseDirectory /var/lib/clamav
    TCPSocket 3310
    Foreground yes
    MaxScanSize {{.Values.clamav.limits.scanSize}}M
    MaxFileSize {{.Values.clamav.limits.fileSize}}M
    StreamMaxLength {{.Values.clamav.limits.scanSize}}M
  freshclam.conf: |
    LogTime yes
    LogVerbose yes
    LogSyslog no
    DatabaseOwner clam
    DatabaseMirror http://{{ include "clamav.fullname" . }}-notify
    {{- range .Values.clamav.freshclam.mirrors }}
    DatabaseMirror {{ . }}
    {{- end }}
    Foreground yes
