apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "clamav.fullname" . }}
spec:
  maxReplicas: {{ .Values.clamav.scaling.maxReplicas }}
  minReplicas: {{ .Values.clamav.scaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "clamav.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.clamav.scaling.cpuTarget }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.clamav.scaling.memoryTarget }}
