kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

environment:
  NOTPROD_KUBE_CERTIFICATE_AUTHORITY: https://raw.githubusercontent.com/UKHomeOffice/acp-ca/master/acp-notprod.crt
  NOTPROD_KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
  NOTPROD_KUBE_CLUSTER_NAME: acp-notprod
  PROD_KUBE_CERTIFICATE_AUTHORITY: https://raw.githubusercontent.com/UKHomeOffice/acp-ca/master/acp-prod.crt
  PROD_KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
  PROD_KUBE_CLUSTER_NAME: acp-prod
  IMAGE_NAME: clamav

steps:

- name: Lint Chart
  image: quay.io/ukhomeofficedigital/helm:v3.4.0
  commands:
    - helm lint ./charts/clamav
  when:
    event: [push, tag]

- name: Deploy to Notprod namespace
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:v3.4.0
  environment:
    USER: helm
    KUBE_NAMESPACE: dq-apps-notprod
    NOTPROD_HELM_KUBETOKEN:
      from_secret: NOTPROD_HELM_KUBETOKEN

  commands:
    - export KUBE_SERVER=$${NOTPROD_KUBE_SERVER}
    - export KUBE_CLUSTER_NAME=$${NOTPROD_KUBE_CLUSTER_NAME}
    - export KUBE_CERTIFICATE_AUTHORITY=$${NOTPROD_KUBE_CERTIFICATE_AUTHORITY}
    - export KUBE_TOKEN=$${NOTPROD_HELM_KUBETOKEN}
    - /setup-kubeconfig.sh
    - helm delete --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME}
    - helm upgrade --install --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME} ./charts/clamav
    # - helm install --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME} ./charts/clamav
  when:
    event:
      - push

- name: Deploy to Prod namespace
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:v3.4.0
  environment:
    USER: helm
    KUBE_NAMESPACE: dq-apps
    PROD_HELM_KUBETOKEN:
      from_secret: PROD_HELM_KUBETOKEN

  commands:
    - export KUBE_SERVER=$${PROD_KUBE_SERVER}
    - export KUBE_CLUSTER_NAME=$${PROD_KUBE_CLUSTER_NAME}
    - export KUBE_CERTIFICATE_AUTHORITY=$${PROD_KUBE_CERTIFICATE_AUTHORITY}
    - export KUBE_TOKEN=$${PROD_HELM_KUBETOKEN}
    - /setup-kubeconfig.sh
    - helm delete --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME}
    - helm upgrade --install --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME} ./charts/clamav
    # - helm install --namespace=$${KUBE_NAMESPACE} $${IMAGE_NAME} ./charts/clamav
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production
