apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: clamav
    meta.helm.sh/release-namespace: dq-apps
  labels:
    app.kubernetes.io/instance: clamav
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dq-clamav
    app.kubernetes.io/version: 0.2.11
    helm.sh/chart: dq-clamav-0.2.11
  name: clamav-notify
  namespace: dq-apps
