# Default values for clamav.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- override the name of the clamav chart
nameOverride: ""

# fullnameOverride -- override the full name of the clamav chart
fullnameOverride: ""

service:
  # service.port -- The port to be used by the clamav service
  port: 443
  # service.ingress -- Specifies ingress rules for the clamav service
  ingress:

serviceAccount:
  # serviceAccount.create -- Should we create the service account and roles
  # create: true
  create: false
  # serviceAccount.name -- The name of the service account used by clamav-notify
  name: clamav-notify
  # serviceAccount.annotations -- Annotaions for the service account used by clamav-notify
  annotations: {}

clamavNotify:
  # clamavNotify.image -- The clamav-notify docker image
  image: quay.io/ukhomeofficedigital/acp-clamav-notify
  # clamavNotify.version -- The clamav-notify docker image version - defaults to .Chart.appVersion
  version: ""
  # clamavNotify.resources -- The resource requests and limits for the clamav-http service
  resources:
    requests:
      cpu: 400m
      memory: 1000M
    limits:
      cpu: 800m
      memory: 2000M
  freshclam:
    # clamavNotify.freshclam.checkFrequency -- The number of checks for new virus definitions per day
    checkFrequency: 24
    # clamavNotify.freshclam.mirrors -- A list of clamav mirrors to be used by the clamav-notify service
    mirrors:
      - db.uk.clamav.net
      - database.clamav.net
  volume:
    # clamavNotify.volume.storageClass -- The storage class of the volume used by clamav-notify
    storageClass: gp2-encrypted
    # clamavNotify.volume.size -- The size class of the volume used by clamav-notify in GB
    size: 5

clamavHTTP:
  # clamavHTTP.image -- The clamav-http docker image
  image: quay.io/ukhomeofficedigital/acp-clamav-http
  # clamavHTTP.version -- The clamav-http docker image version - defaults to .Chart.appVersion
  version: ""
  resources:
    # clamavHTTP.resources -- The resource requests and limits for the clamav-http service
    requests:
      cpu: 1000m
      memory: 2000M
      ephemeral-storage: "500M"
    limits:
      cpu: 1500m
      memory: 3000M
      ephemeral-storage: "1000M"

clamavNotifyCron:
  # clamavNotifyCron.image -- The clamav-notify-cron docker image
  image: quay.io/ukhomeofficedigital/acp-clamav-notify-cron
  # clamavNotify.version -- The clamav-notify-cron docker image version - defaults to .Chart.appVersion
  version: ""
  # clamavNotifyCron.schedule -- The cron schedule for loading updated signatures
  schedule:  "*/15 * * * *"

clamav:
  # clamav.image -- The clamav docker image
  image: quay.io/ukhomeofficedigital/acp-clamav
  # clamav.version -- The clamav docker image version - defaults to .Chart.appVersion
  version: ""
  freshclam:
    # clamav.freshclam.mirrors -- A list of clamav mirrors to be used by the clamav service
    mirrors:
      - db.uk.clamav.net
      - database.clamav.net
  certificate:
    # clamav.certificate.create -- Should a certificate be created for the clamav service
    create: true
    # clamav.certificate.secretName -- Override the default certificate secret name
    secretName: ""
    # clamav.certificate.issuer -- The issuer to use when creating a certificate
    issuer:
      name: platform-ca
      kind: ClusterIssuer
  scaling:
    # clamav.scaling.minReplicas -- The minumum number of clamav replicas
    minReplicas: 2
    # clamav.scaling.maxReplicas -- The maximum number of clamav replicas
    maxReplicas: 20
    # clamav.scaling.cpuTarget -- The target cpu usage percentage for clamav
    cpuTarget: 30
    # clamav.scaling.memoryTarget -- The target memory usage percentage for clamav
    memoryTarget: 30
  limits:
    # clamav.limits.fileSize -- The largest file size scanable by clamav, in MB
    fileSize: 20
    # clamav.limits.scanSize -- The largest scan size permitted in clamav, in MB
    scanSize: 100
  resources:
    # clamav.resources -- The resource requests and limits for the clamav service
    requests:
      cpu: 1000m
      memory: 2000M
      ephemeral-storage: "500M"
    limits:
      cpu: 1500m
      memory: 3000M
      ephemeral-storage: "1000M"
nginxProxy:
  # nginxProxy.image -- The nginx proxy docker image
  image: quay.io/ukhomeofficedigital/nginx-proxy
  # nginxProxy.version -- The nginx proxy docker image version
  version: v3.4.20
  # nginxProxy.resources -- The resource requests and limits for the nginx proxy service
  resources:
    requests:
      cpu: 1000m
      memory: 2000M
      ephemeral-storage: "500M"
    limits:
      cpu: 1500m
      memory: 3000M
      ephemeral-storage: "1000M"
